apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-secop
  labels:
    app: dev-secop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-secop
  strategy:
    type: RollingUpdate
    RollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: dev-secop
    spec: