name: Node.js Backend and React Frontend Deployment

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install backend dependencies
      working-directory: ./app/backend
      run: npm ci
    - name: Build backend
      working-directory: ./app/backend
      run: npm run build --if-present
    - name: Test backend
      working-directory: ./app/backend
      run: npm test || echo "No tests found for backend"

  build-and-test-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js for React
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install frontend dependencies
      working-directory: ./app/frontend
      run: |
        npm ci
        npm install react-scripts
    - name: Build React app
      working-directory: ./app/frontend
      run: CI=false npm run build
    - name: Test React app
      working-directory: ./app/frontend
      run: CI=true npm test -- --passWithNoTests || echo "No tests found for frontend"